#! /bin/sh

feh --bg-fill $HOME/images/wallpapers/Konachan.com\ -\ 171348\ clouds\ flowers\ grass\ nobody\ original\ realistic\ scenic\ sky\ soyokaze.jpg &
picom &
$HOME/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='^4' follow=off
bspc rule -a qutebrowser desktop='^1' follow=off
bspc rule -a MongoDB\ Compass desktop='^5' follow=off
